#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v19
# autospec commit: f35655a
#
Name     : R-fda
Version  : 6.2.0
Release  : 66
URL      : https://cran.r-project.org/src/contrib/fda_6.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fda_6.2.0.tar.gz
Summary  : Functional Data Analysis
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-deSolve
Requires: R-fds
BuildRequires : R-deSolve
BuildRequires : R-fds
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
analysis as described in Ramsay, J. O. and Silverman, B. W.

%prep
%setup -q -n fda
pushd ..
cp -a fda buildavx2
popd
pushd ..
cp -a fda buildavx512
popd
pushd ..
cp -a fda buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726671835

%install
export SOURCE_DATE_EPOCH=1726671835
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fda/DESCRIPTION
/usr/lib64/R/library/fda/INDEX
/usr/lib64/R/library/fda/Meta/Rd.rds
/usr/lib64/R/library/fda/Meta/data.rds
/usr/lib64/R/library/fda/Meta/demo.rds
/usr/lib64/R/library/fda/Meta/features.rds
/usr/lib64/R/library/fda/Meta/hsearch.rds
/usr/lib64/R/library/fda/Meta/links.rds
/usr/lib64/R/library/fda/Meta/nsInfo.rds
/usr/lib64/R/library/fda/Meta/package.rds
/usr/lib64/R/library/fda/Meta/vignette.rds
/usr/lib64/R/library/fda/NAMESPACE
/usr/lib64/R/library/fda/NEWS.Rd
/usr/lib64/R/library/fda/R/fda
/usr/lib64/R/library/fda/R/fda.rdb
/usr/lib64/R/library/fda/R/fda.rdx
/usr/lib64/R/library/fda/data/Rdata.rdb
/usr/lib64/R/library/fda/data/Rdata.rds
/usr/lib64/R/library/fda/data/Rdata.rdx
/usr/lib64/R/library/fda/demo/ElectricDemand.R
/usr/lib64/R/library/fda/demo/canadian-weather.R
/usr/lib64/R/library/fda/demo/gait.R
/usr/lib64/R/library/fda/demo/goodsindex.R
/usr/lib64/R/library/fda/demo/growth.R
/usr/lib64/R/library/fda/demo/growthreg.R
/usr/lib64/R/library/fda/demo/growthsetup.R
/usr/lib64/R/library/fda/demo/growthsmooth.R
/usr/lib64/R/library/fda/demo/handwrit.R
/usr/lib64/R/library/fda/demo/handwrit.pda.R
/usr/lib64/R/library/fda/demo/lip.R
/usr/lib64/R/library/fda/demo/pinch.R
/usr/lib64/R/library/fda/demo/weatherANOVA.R
/usr/lib64/R/library/fda/doc/BasisBasics.R
/usr/lib64/R/library/fda/doc/BasisBasics.Rmd
/usr/lib64/R/library/fda/doc/BasisBasics.html
/usr/lib64/R/library/fda/doc/index.html
/usr/lib64/R/library/fda/doc/monotoneFunctions.R
/usr/lib64/R/library/fda/doc/monotoneFunctions.Rmd
/usr/lib64/R/library/fda/doc/monotoneFunctions.html
/usr/lib64/R/library/fda/doc/splineFunctions.R
/usr/lib64/R/library/fda/doc/splineFunctions.Rmd
/usr/lib64/R/library/fda/doc/splineFunctions.html
/usr/lib64/R/library/fda/help/AnIndex
/usr/lib64/R/library/fda/help/aliases.rds
/usr/lib64/R/library/fda/help/fda.rdb
/usr/lib64/R/library/fda/help/fda.rdx
/usr/lib64/R/library/fda/help/paths.rds
/usr/lib64/R/library/fda/html/00Index.html
/usr/lib64/R/library/fda/html/R.css
/usr/lib64/R/library/fda/scripts/afda-ch01.R
/usr/lib64/R/library/fda/scripts/afda-ch02.R
/usr/lib64/R/library/fda/scripts/afda-ch03.R
/usr/lib64/R/library/fda/scripts/afda-ch04.R
/usr/lib64/R/library/fda/scripts/afda-ch05.R
/usr/lib64/R/library/fda/scripts/afda-ch06.R
/usr/lib64/R/library/fda/scripts/afda-ch07.R
/usr/lib64/R/library/fda/scripts/fda-ch01.R
/usr/lib64/R/library/fda/scripts/fda-ch02.R
/usr/lib64/R/library/fda/scripts/fda-ch03.R
/usr/lib64/R/library/fda/scripts/fda-ch07.R
/usr/lib64/R/library/fda/scripts/fda-ch08.R
/usr/lib64/R/library/fda/scripts/fda-ch13.R
/usr/lib64/R/library/fda/scripts/fda-ch17.R
/usr/lib64/R/library/fda/scripts/fdarm-ch01.R
/usr/lib64/R/library/fda/scripts/fdarm-ch02.R
/usr/lib64/R/library/fda/scripts/fdarm-ch03.R
/usr/lib64/R/library/fda/scripts/fdarm-ch04.R
/usr/lib64/R/library/fda/scripts/fdarm-ch05.R
/usr/lib64/R/library/fda/scripts/fdarm-ch06.R
/usr/lib64/R/library/fda/scripts/fdarm-ch07.R
/usr/lib64/R/library/fda/scripts/fdarm-ch08.R
/usr/lib64/R/library/fda/scripts/fdarm-ch09.R
/usr/lib64/R/library/fda/scripts/fdarm-ch10.R
/usr/lib64/R/library/fda/scripts/fdarm-ch11.R
